#!/bin/zsh

function proxy_on() {
    export http_proxy=http://proxy.iil.intel.com:911
    export https_proxy=$http_proxy
    export ftp_proxy=$http_proxy
    export rsync_proxy=$http_proxy
    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"

    export HTTP_PROXY=$http_proxy
    export HTTPS_PROXY=$http_proxy
    export FTP_PROXY=$http_proxy
    export RSYNC_PROXY=$http_proxy
    export NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"

    git config --global http.proxy $http_proxy 
    git config --global https.proxy $http_proxy
}

function proxy_off() {
    unset http_proxy
    unset https_proxy
    unset ftp_proxy
    unset rsync_proxy
    unset no_proxy
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset FTP_PROXY
    unset RSYNC_PROXY
    unset NO_PROXY
    git config --global --unset http.proxy
    git config --global --unset https.proxy
}


